export const ADD_FORM = 'ADD_FORM';

export const GET_USER_NAME = 'GET_USER_NAME';
export const ERROR_USER_DONT_EXIST = 'ERROR_USER_DONT_EXIST';

export const GET_FORM_NAME = 'GET_FORM_NAME';
export const ERROR_FORM_DONT_EXIST = 'ERROR_FORM_DONT_EXIST';
