export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SET_ANSWERS = 'SET_ANSWERS';

export const GET_USER_NAME = 'GET_USER_NAME';
export const ERROR_USER_DONT_EXIST = 'ERROR_USER_DONT_EXIST';

export const GET_FORM_NAME = 'GET_FORM_NAME';
export const ERROR_FORM_DONT_EXIST = 'ERROR_FORM_DONT_EXIST';

export const SET_TAGS = 'SET_TAGS';
export const ADD_TAG = 'ADD_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';
export const DRAW_RESULT = 'DRAW_RESULT';
export const ERROR_DRAW_RESULT = 'ERROR_DRAW_RESULT';
export const SET_ERROR_DRAW_RESULT = 'SET_ERROR_DRAW_RESULT';
