name: Check build
on:
  pull_request:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15.10.0 ]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
      - name: Install Packages
        run: npm install
      - name: Build production page
        env:
          LAST_UPDATE_DATE: ${{ steps.date.outputs.date }}
        run: npm run build
