name: Deploy Storybook and Test page
on:
  push:
    branches:
      - master
jobs:
  deploy_page:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15.10.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
      - name: Install depedencies
        run: npm install
      - name: Build page
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_DATABASE_URL: ${{ secrets.REACT_APP_DATABASE_URL }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
          PUBLIC_URL: "https://kurczaczkowe-rzeczy.github.io/randomizator"
          REACT_APP_ENVIRONMENT: "development"
          BUILD_PATH: "./build"
          SKIP_PREFLIGHT_CHECK: true
          REACT_APP_LAST_UPDATE_DATE: ${{ steps.date.outputs.date }}
        run: npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
          publish_branch: gh-pages
  deploy_storybook:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15.10.0 ]
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v2.3.0
            with:
              node-version: ${{ matrix.node-version }}
          - name: Install depedencies
            run: |
              npm i
              npm i -g firebase-tools
          - name: Setup storybook
            run: |
              npm run build-storybook
              firebase target:apply hosting stories randomizator-stories
          - name: Deploy storybook
            run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting:stories
  bump_version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15.10.0 ]
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v2.3.0
            with:
              node-version: ${{ matrix.node-version }}
          -name: Bump version
            run: |
              git config --global user.email "lzygmunt0@gmail.com"
              git config --global user.name "KurczaczekBumperBot"
              npm run bump
              git push --follow-tags
