name: Deploy Production Page
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15.10.0 ]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
      - name: Install Packages
        run: npm install; npm i -g firebase-tools
      - name: Build production page
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY_PROD }}
          REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID_PROD }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN_PROD }}
          REACT_APP_DATABASE_URL: ${{ secrets.REACT_APP_DATABASE_URL_PROD }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET_PROD }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID_PROD }}
          REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID_PROD }}
          PUBLIC_URL: "https://randomizator.web.app"
          REACT_APP_ENVIRONMENT: "production"
          BUILD_PATH: "./build.prod"
          SKIP_PREFLIGHT_CHECK: true
          REACT_APP_LAST_UPDATE_DATE: ${{ steps.date.outputs.date }}
        run: npm run build
      - name: Deploy production
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting:app
